### ISSUE TITLE
The parser could be replaced by this Nuget package

### ISSUE THREAD

**Issue by maximilien-noal** [JorisVanEijden/Structurizer#1]
https://github.com/xoofx/CppAst.NET

I've known about it for years, I think I've found the very first project where it is justified to use it. :)

There is also this one: 

https://github.com/mono/CppSharp

But I think the first one is more appropriate / sufficient.

**Comment by JorisVanEijden** [comment]
I already tried both before deciding to build my own.

CppAst I couldn't even get to work due to messed up libclang dependencies.
> The target primary usage of this library is to serve as a simple foundation for domain oriented PInvoke/Interop codegen

Which is quite far removed from our goal.

But even then, they transform the header files into C# _code_ (not data) or into syntax tree models that are even harder to convert to what we need than the original C headers.

https://github.com/fanghm/c-header-parser sounds exactly like what we need:
> This program can parse C header files to extract the struct/union/enum definitions, and with these definitions to analyse the memory dump data of the struct/union. The analysis result can be printed in a nice format with both the stuct/union member names and their values.

So I started a C# port, but that was also way more complex than needed to parse the standardized machine-generated output of IDA and Ghidra. And it actually failed to understand some of the syntax used.

I agree that being able to reliably parse _any_ C header for struct/enum info would be nice to have, but it feels a bit too ambitious for now.

So here we are :)
